services:
  - type: worker
    name: zayavki-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: SHEET_ID
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
      - key: DATA_DIR
        value: /opt/render/project/src
    autoDeploy: false
